"""create raw table

Revision ID: 97fb73e861e2
Revises: 
Create Date: 2026-06-20 13:19:35.204738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97fb73e861e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cp', sa.String(length=5), nullable=True),
    sa.Column('pop', sa.String(length=5), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('ville', sa.String(length=255), nullable=True),
    sa.Column('departement', sa.String(length=100), nullable=True),
    sa.Column('code_departement', sa.String(length=5), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('code_region', sa.String(length=5), nullable=True),
    sa.Column('latitude_raw', sa.String(length=30), nullable=True),
    sa.Column('longitude_raw', sa.String(length=30), nullable=True),
    sa.Column('horaires', sa.Text(), nullable=True),
    sa.Column('services', sa.Text(), nullable=True),
    sa.Column('prix', sa.Text(), nullable=True),
    sa.Column('rupture', sa.Text(), nullable=True),
    sa.Column('geom', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('carburants_disponibles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('carburants_indisponibles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('services_service', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gazole_maj', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gazole_prix', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('sp95_maj', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sp95_prix', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('e85_maj', sa.DateTime(timezone=True), nullable=True),
    sa.Column('e85_prix', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('gplc_maj', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gplc_prix', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('e10_maj', sa.DateTime(timezone=True), nullable=True),
    sa.Column('e10_prix', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('sp98_maj', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sp98_prix', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('e10_rupture_debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('e10_rupture_type', sa.String(length=50), nullable=True),
    sa.Column('sp98_rupture_debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sp98_rupture_type', sa.String(length=50), nullable=True),
    sa.Column('sp95_rupture_debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sp95_rupture_type', sa.String(length=50), nullable=True),
    sa.Column('e85_rupture_debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('e85_rupture_type', sa.String(length=50), nullable=True),
    sa.Column('gplc_rupture_debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gplc_rupture_type', sa.String(length=50), nullable=True),
    sa.Column('gazole_rupture_debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gazole_rupture_type', sa.String(length=50), nullable=True),
    sa.Column('carburants_rupture_temporaire', sa.Text(), nullable=True),
    sa.Column('carburants_rupture_definitive', sa.Text(), nullable=True),
    sa.Column('horaires_automate_24_24', sa.String(length=10), nullable=True),
    sa.Column('horaires_jour', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw')
    # ### end Alembic commands ###
